extension_paths={
    'noname': 'others',
    #files
    '.pdf': 'files',
    '.doc': 'files',
    '.docx': 'files',
    '.txt': 'files',
    '.xls': 'files',
    '.xlsx': 'files',
    '.ppt': 'files',
    '.pptx': 'files',
    'odt': 'files',
    '.rtf': 'files',
    '.tex': 'files',
    '.wks': 'files',
    '.wps': 'files',
    '.wpd': 'files',

    #images
    '.jpg': 'images',
    '.jpeg': 'images',
    '.png': 'images',
    '.gif': 'images',
    '.bmp': 'images',
    '.svg': 'images',
    '.ico': 'images',

    #videos
    '.mp4': 'video',
    '.mkv': 'video',
    '.webm': 'video',
    '.flv': 'video',
    '.vob': 'video',
    '.ogv': 'video',
    '.ogg': 'video',
    '.drc': 'video',
    '3gp': 'video',
    '.3gp2': 'video',
    '.3g2': 'video',
    '.wmv': 'video',
    '.avi': 'video',
    '.mov': 'video',

    #audio
    '.mp3': 'audio',
    '.wav': 'audio',
    '.aac': 'audio',
    '.aa': 'audio',
    '.dvf': 'audio',
    '.m4a': 'audio',
    '.m4b': 'audio',
    '.m4p': 'audio',
    '.m4r': 'audio',
    '.m4v': 'audio',
    '.3ga': 'audio',
    '.act': 'audio',
    '.aiff': 'audio',
    '.amr': 'audio',
    '.ape': 'audio',
    '.au': 'audio',
    '.awb': 'audio',
    '.dct': 'audio',
    '.dss': 'audio',
    '.flac': 'audio',
    '.gsm': 'audio',
    '.iklax': 'audio',
    '.ivs': 'audio',
    '.m3u': 'audio',
    '.m4p': 'audio',
    '.mmf': 'audio',
    '.mpc': 'audio',
    '.msv': 'audio',
    '.oga': 'audio',
    '.opus': 'audio',
    '.ra': 'audio',
    '.rm': 'audio',
    '.raw': 'audio',
    '.sln': 'audio',
    '.tta': 'audio',
    '.vox': 'audio',
    '.wma': 'audio',
    '.wv': 'audio',
    '.webm': 'audio',
    '.8svx': 'audio',

    #compressed
    '.zip': 'zip',
    '.rar': 'zip',
    '.7z': 'zip',
    '.tar': 'zip',
    '.gz': 'zip',
    '.bz2': 'zip',
    '.xz': 'zip',
    '.iso': 'zip',
    '.dmg': 'zip',
    '.cpio': 'zip',
    '.7zip': 'zip',
    '.arj': 'zip',
    '.deb': 'zip',
    '.pkg': 'zip',
    '.rpm': 'zip',
    '.z': 'zip',
    '.taz': 'zip',
    '.tgz': 'zip',
    '.zst': 'zip',
    '.lz': 'zip',
    '.lzma': 'zip',
    '.lzo': 'zip',
    '.rz': 'zip',
    '.shar': 'zip',
    '.snappy': 'zip',
    '.snap': 'zip',
    '.zpaq': 'zip',
    '.zoo': 'zip',
    
    #executable
    '.exe': 'other',
    '.msi': 'other',
    '.apk': 'other',
    '.jar': 'other',
    '.bat': 'other',
    '.sh': 'other',
    '.py': 'other',
    '.c': 'other',
    '.cpp': 'other',
    '.java': 'other',
    '.class': 'other',
    '.html': 'other',
    '.css': 'other',
    '.js': 'other',
    '.php': 'other',
    '.json': 'other',
    '.xml': 'other',
    '.sql': 'other',
    '.db': 'other',
    '.dbf': 'other',
    '.mdb': 'other',
    
    '.torrent': 'other',
    '.url': 'other',
    '.lnk': 'other',

    #system
    '.ini': 'other',
    '.dll': 'other',
    '.sys': 'other',
    '.tmp': 'other'
}